In [85]:
!pip install torch torchvision

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.23.0+cu126)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [86]:
import torch
import torch.nn.functional as F
import torch.nn as nn
from torch.autograd import grad

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [87]:
from sklearn import datasets
iris = datasets.load_iris()

посмотрим данные

In [88]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [89]:
iris_df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

нет пропущенных данных

замена значений на числовые

In [90]:
species_mapping = {'setosa': 0, 'versicolor': 1, 'virginica': 2}
iris_df['species'] = iris_df['species'].map(species_mapping)

In [91]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(4, 8),
            nn.ReLU(),
            nn.Linear(8, 6),
            nn.ReLU(),
            nn.Linear(6, 3),
        )

    def forward(self, x):
        return self.layers(x)

torch.manual_seed(42)
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=6, bias=True)
    (3): ReLU()
    (4): Linear(in_features=6, out_features=3, bias=True)
  )
)

In [92]:
with torch.no_grad():
  x=torch.rand((1, 4))
  y=model(x)
  out=torch.softmax(y, dim=1)
print(out)

tensor([[0.4036, 0.2728, 0.3236]])

разделение на выборки, нормализация

In [93]:
X = iris.data
Y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [94]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, X, Y):
        self.features = X
        self.labels = Y

    def __getitem__(self, index):
        x = self.features[index]
        y = self.labels[index]
        return x, y

    def __len__(self):
        return len(self.features)

train_dataset = MyDataset(X_train, Y_train)
test_dataset = MyDataset(X_test, Y_test)

загрузчики

In [95]:
train_dataloader = torch.utils.data.DataLoader(
    train_dataset, batch_size=2, shuffle=True, num_workers=0)

test_dataloader = torch.utils.data.DataLoader(
    test_dataset, batch_size=2, shuffle=False, num_workers=0)

In [96]:
for (idx, (x, y)) in enumerate(train_dataloader):
    print(f'Batch: #{idx}, \nx: {x}, \ny: {y}')

Batch: #0,
x: tensor([[ 2.2191, -0.5560,  1.6637,  1.0468],
        [-1.4827,  0.3396, -1.3457, -1.3233]], dtype=torch.float64),
y: tensor([2, 0])
Batch: #1,
x: tensor([[-1.0051,  1.0112, -1.2322, -0.7966],
        [-0.6468,  1.4590, -1.2889, -1.3233]], dtype=torch.float64),
y: tensor([0, 0])
Batch: #2,
x: tensor([[-1.6022, -1.6754, -1.4025, -1.1916],
        [-0.0498, -0.7799,  0.1874, -0.2699]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #3,
x: tensor([[ 1.0250,  0.5635,  1.0959,  1.1784],
        [-1.2439,  0.7873, -1.2322, -1.3233]], dtype=torch.float64),
y: tensor([2, 0])
Batch: #4,
x: tensor([[-0.5274,  0.7873, -1.2889, -1.0599],
        [-1.2439, -0.1082, -1.3457, -1.1916]], dtype=torch.float64),
y: tensor([0, 0])
Batch: #5,
x: tensor([[-0.4080,  2.5784, -1.3457, -1.3233],
        [ 0.6667, -0.3321,  0.3009,  0.1251]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #6,
x: tensor([[-0.8857,  0.7873, -1.2889, -1.3233],
        [ 0.1891, -0.3321,  0.4145,  0.3884]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #7,
x: tensor([[-0.8857,  0.5635, -1.1754, -0.9283],
        [ 1.0250,  0.5635,  1.0959,  1.7051]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #8,
x: tensor([[ 0.1891, -1.8993,  0.1306, -0.2699],
        [-0.2886, -0.1082,  0.4145,  0.3884]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #9,
x: tensor([[-1.0051,  1.0112, -1.4025, -1.1916],
        [ 0.3085, -0.1082,  0.4713,  0.2568]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #10,
x: tensor([[1.6221, 0.3396, 1.2662, 0.7834],
        [0.5473, 0.5635, 1.2662, 1.7051]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #11,
x: tensor([[-1.1245,  1.2351, -1.3457, -1.4549],
        [ 0.5473, -0.3321,  1.0391,  0.7834]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #12,
x: tensor([[ 1.0250,  0.1157,  0.5281,  0.3884],
        [-0.4080, -1.4515, -0.0397, -0.2699]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #13,
x: tensor([[-0.4080, -1.4515,  0.0170, -0.1383],
        [-1.1245,  0.1157, -1.2889, -1.4549]], dtype=torch.float64),
y: tensor([1, 0])
Batch: #14,
x: tensor([[-0.1692,  3.0262, -1.2889, -1.0599],
        [-0.4080,  1.0112, -1.4025, -1.3233]], dtype=torch.float64),
y: tensor([0, 0])
Batch: #15,
x: tensor([[ 0.3085, -0.5560,  0.1306,  0.1251],
        [ 1.6221, -0.1082,  1.1527,  0.5201]], dtype=torch.float64),
y: tensor([1, 2])
Batch: #16,
x: tensor([[-0.1692, -0.3321,  0.2442,  0.1251],
        [ 0.7861,  0.3396,  0.7552,  1.0468]], dtype=torch.float64),
y: tensor([1, 2])
Batch: #17,
x: tensor([[-0.8857,  1.6829, -1.2322, -1.3233],
        [ 0.4279, -1.8993,  0.4145,  0.3884]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #18,
x: tensor([[-0.8857,  1.0112, -1.3457, -1.1916],
        [-0.0498, -0.7799,  0.7552,  0.9151]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #19,
x: tensor([[-0.1692, -0.5560,  0.1874,  0.1251],
        [-1.1245,  0.1157, -1.2889, -1.3233]], dtype=torch.float64),
y: tensor([1, 0])
Batch: #20,
x: tensor([[ 1.0250, -0.1082,  0.8120,  1.4418],
        [ 1.0250,  0.1157,  0.3577,  0.2568]], dtype=torch.float64),
y: tensor([2, 1])
Batch: #21,
x: tensor([[ 2.0997, -0.1082,  1.6069,  1.1784],
        [-0.1692, -1.2277,  0.6984,  1.0468]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #22,
x: tensor([[-0.4080, -1.6754,  0.1306,  0.1251],
        [ 1.0250, -1.2277,  1.1527,  0.7834]], dtype=torch.float64),
y: tensor([1, 2])
Batch: #23,
x: tensor([[-0.8857,  1.6829, -1.2889, -1.1916],
        [ 2.4580,  1.6829,  1.4934,  1.0468]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #24,
x: tensor([[-1.2439,  0.1157, -1.2322, -1.3233],
        [-0.1692, -0.1082,  0.2442, -0.0066]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #25,
x: tensor([[-1.0051, -2.3471, -0.1533, -0.2699],
        [-1.8410, -0.1082, -1.5161, -1.4549]], dtype=torch.float64),
y: tensor([1, 0])
Batch: #26,
x: tensor([[-0.2886, -0.1082,  0.1874,  0.1251],
        [-0.5274,  1.9068, -1.4025, -1.0599]], dtype=torch.float64),
y: tensor([1, 0])
Batch: #27,
x: tensor([[-1.0051,  1.2351, -1.3457, -1.3233],
        [-0.5274,  1.9068, -1.1754, -1.0599]], dtype=torch.float64),
y: tensor([0, 0])
Batch: #28,
x: tensor([[ 0.4279,  0.7873,  0.9255,  1.4418],
        [-1.3633,  0.3396, -1.4025, -1.3233]], dtype=torch.float64),
y: tensor([2, 0])
Batch: #29,
x: tensor([[ 0.6667, -0.5560,  1.0391,  1.1784],
        [-1.0051,  0.3396, -1.4593, -1.3233]], dtype=torch.float64),
y: tensor([2, 0])
Batch: #30,
x: tensor([[-1.4827,  0.1157, -1.2889, -1.3233],
        [-1.0051, -0.1082, -1.2322, -1.3233]], dtype=torch.float64),
y: tensor([0, 0])
Batch: #31,
x: tensor([[ 1.2638,  0.3396,  1.0959,  1.4418],
        [-1.1245, -1.2277,  0.4145,  0.6518]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #32,
x: tensor([[ 2.2191, -0.1082,  1.3230,  1.4418],
        [ 1.6221,  1.2351,  1.3230,  1.7051]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #33,
x: tensor([[ 1.1444, -0.5560,  0.5848,  0.2568],
        [ 0.0697, -0.1082,  0.7552,  0.7834]], dtype=torch.float64),
y: tensor([1, 2])
Batch: #34,
x: tensor([[-0.1692, -1.0038, -0.1533, -0.2699],
        [ 0.5473, -1.6754,  0.3577,  0.1251]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #35,
x: tensor([[-0.7662,  1.0112, -1.2889, -1.3233],
        [-1.1245, -0.1082, -1.3457, -1.3233]], dtype=torch.float64),
y: tensor([0, 0])
Batch: #36,
x: tensor([[ 2.2191, -1.0038,  1.7773,  1.4418],
        [-1.4827,  0.7873, -1.3457, -1.1916]], dtype=torch.float64),
y: tensor([2, 0])
Batch: #37,
x: tensor([[-0.8857, -1.2277, -0.4372, -0.1383],
        [-0.1692, -0.5560,  0.4145,  0.1251]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #38,
x: tensor([[-1.2439, -0.1082, -1.3457, -1.4549],
        [ 0.5473,  0.7873,  1.0391,  1.5734]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #39,
x: tensor([[-0.7662, -0.7799,  0.0738,  0.2568],
        [-0.4080, -1.2277,  0.1306,  0.1251]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #40,
x: tensor([[-1.2439,  0.7873, -1.0618, -1.3233],
        [-0.2886, -0.7799,  0.2442,  0.1251]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #41,
x: tensor([[-0.2886, -0.5560,  0.6416,  1.0468],
        [ 0.6667,  0.3396,  0.8688,  1.4418]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #42,
x: tensor([[ 1.5026, -0.1082,  1.2094,  1.1784],
        [-1.0051,  0.7873, -1.2322, -1.0599]], dtype=torch.float64),
y: tensor([2, 0])
Batch: #43,
x: tensor([[ 0.5473, -1.2277,  0.6984,  0.9151],
        [ 0.7861, -0.5560,  0.4713,  0.3884]], dtype=torch.float64),
y: tensor([2, 1])
Batch: #44,
x: tensor([[ 0.1891, -1.8993,  0.6984,  0.3884],
        [ 0.6667,  0.1157,  0.9823,  0.7834]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #45,
x: tensor([[ 0.0697,  0.3396,  0.5848,  0.7834],
        [-0.0498, -0.7799,  0.7552,  0.9151]], dtype=torch.float64),
y: tensor([1, 2])
Batch: #46,
x: tensor([[1.2638, 0.1157, 0.6416, 0.3884],
        [2.2191, 1.6829, 1.6637, 1.3101]], dtype=torch.float64),
y: tensor([1, 2])
Batch: #47,
x: tensor([[ 0.6667, -0.7799,  0.8688,  0.9151],
        [ 1.1444,  0.3396,  1.2094,  1.4418]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #48,
x: tensor([[-0.0498, -1.0038,  0.1306, -0.0066],
        [-0.4080, -1.0038,  0.3577, -0.0066]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #49,
x: tensor([[-1.3633,  0.3396, -1.2322, -1.3233],
        [ 1.8609, -0.5560,  1.3230,  0.9151]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #50,
x: tensor([[-0.0498, -0.5560,  0.7552,  1.5734],
        [ 0.5473, -0.7799,  0.6416,  0.7834]], dtype=torch.float64),
y: tensor([2, 2])
Batch: #51,
x: tensor([[ 1.1444, -0.1082,  0.9823,  1.1784],
        [ 0.1891, -0.7799,  0.7552,  0.5201]], dtype=torch.float64),
y: tensor([2, 1])
Batch: #52,
x: tensor([[ 0.1891,  0.7873,  0.4145,  0.5201],
        [-0.2886, -0.3321, -0.0965,  0.1251]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #53,
x: tensor([[-0.0498, -0.7799,  0.0738, -0.0066],
        [ 0.4279, -0.3321,  0.3009,  0.1251]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #54,
x: tensor([[-1.7216, -0.3321, -1.3457, -1.3233],
        [ 0.5473, -1.2277,  0.6416,  0.3884]], dtype=torch.float64),
y: tensor([0, 1])
Batch: #55,
x: tensor([[-0.8857,  1.4590, -1.2889, -1.0599],
        [ 1.2638,  0.1157,  0.9255,  1.1784]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #56,
x: tensor([[-0.7662,  2.3546, -1.2889, -1.4549],
        [ 0.5473, -0.5560,  0.7552,  0.3884]], dtype=torch.float64),
y: tensor([0, 2])
Batch: #57,
x: tensor([[ 1.3832,  0.3396,  0.5281,  0.2568],
        [ 0.0697, -0.1082,  0.2442,  0.3884]], dtype=torch.float64),
y: tensor([1, 1])
Batch: #58,
x: tensor([[ 0.3085, -0.5560,  0.5281, -0.0066],
        [-0.8857,  1.6829, -1.0618, -1.0599]], dtype=torch.float64),
y: tensor([1, 0])
Batch: #59,
x: tensor([[-0.8857,  1.0112, -1.3457, -1.3233],
        [ 0.4279, -0.5560,  0.5848,  0.7834]], dtype=torch.float64),
y: tensor([0, 2])

обучение

In [97]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

num_epochs = 50
for epoch in range(num_epochs):
    model.train()

    for (idx, (x, y)) in enumerate(train_dataloader):
        x = x.float()

        model_result = model(x)
        loss = F.cross_entropy(model_result, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f'Batch: #{epoch}/{idx}, loss: {loss:.2f}')

Batch: #0/0, loss: 1.35
Batch: #0/1, loss: 0.98
Batch: #0/2, loss: 1.33
Batch: #0/3, loss: 1.32
Batch: #0/4, loss: 1.15
Batch: #0/5, loss: 1.30
Batch: #0/6, loss: 1.29
Batch: #0/7, loss: 1.28
Batch: #0/8, loss: 0.98
Batch: #0/9, loss: 1.29
Batch: #0/10, loss: 1.09
Batch: #0/11, loss: 1.15
Batch: #0/12, loss: 1.31
Batch: #0/13, loss: 1.04
Batch: #0/14, loss: 1.04
Batch: #0/15, loss: 1.09
Batch: #0/16, loss: 1.13
Batch: #0/17, loss: 1.11
Batch: #0/18, loss: 1.21
Batch: #0/19, loss: 1.04
Batch: #0/20, loss: 0.96
Batch: #0/21, loss: 0.93
Batch: #0/22, loss: 0.98
Batch: #0/23, loss: 1.11
Batch: #0/24, loss: 1.05
Batch: #0/25, loss: 1.23
Batch: #0/26, loss: 1.26
Batch: #0/27, loss: 1.10
Batch: #0/28, loss: 1.21
Batch: #0/29, loss: 0.91
Batch: #0/30, loss: 1.08
Batch: #0/31, loss: 0.89
Batch: #0/32, loss: 1.05
Batch: #0/33, loss: 1.03
Batch: #0/34, loss: 1.22
Batch: #0/35, loss: 1.26
Batch: #0/36, loss: 1.01
Batch: #0/37, loss: 1.09
Batch: #0/38, loss: 1.00
Batch: #0/39, loss: 1.21
Batch: #0/40, loss: 1.11
Batch: #0/41, loss: 1.08
Batch: #0/42, loss: 1.30
Batch: #0/43, loss: 1.08
Batch: #0/44, loss: 1.29
Batch: #0/45, loss: 1.14
Batch: #0/46, loss: 1.19
Batch: #0/47, loss: 1.06
Batch: #0/48, loss: 0.99
Batch: #0/49, loss: 1.19
Batch: #0/50, loss: 0.89
Batch: #0/51, loss: 1.12
Batch: #0/52, loss: 1.01
Batch: #0/53, loss: 1.19
Batch: #0/54, loss: 1.23
Batch: #0/55, loss: 1.18
Batch: #0/56, loss: 1.09
Batch: #0/57, loss: 1.06
Batch: #0/58, loss: 1.07
Batch: #0/59, loss: 1.20
Batch: #1/0, loss: 1.06
Batch: #1/1, loss: 1.06
Batch: #1/2, loss: 0.88
Batch: #1/3, loss: 0.87
Batch: #1/4, loss: 1.17
Batch: #1/5, loss: 1.06
Batch: #1/6, loss: 1.16
Batch: #1/7, loss: 0.99
Batch: #1/8, loss: 1.17
Batch: #1/9, loss: 1.20
Batch: #1/10, loss: 1.05
Batch: #1/11, loss: 1.07
Batch: #1/12, loss: 1.04
Batch: #1/13, loss: 1.20
Batch: #1/14, loss: 1.00
Batch: #1/15, loss: 1.05
Batch: #1/16, loss: 1.19
Batch: #1/17, loss: 0.85
Batch: #1/18, loss: 1.17
Batch: #1/19, loss: 1.07
Batch: #1/20, loss: 1.17
Batch: #1/21, loss: 1.03
Batch: #1/22, loss: 1.11
Batch: #1/23, loss: 0.96
Batch: #1/24, loss: 1.17
Batch: #1/25, loss: 1.08
Batch: #1/26, loss: 1.07
Batch: #1/27, loss: 1.08
Batch: #1/28, loss: 1.26
Batch: #1/29, loss: 0.94
Batch: #1/30, loss: 1.22
Batch: #1/31, loss: 0.86
Batch: #1/32, loss: 1.03
Batch: #1/33, loss: 1.16
Batch: #1/34, loss: 1.16
Batch: #1/35, loss: 1.16
Batch: #1/36, loss: 0.96
Batch: #1/37, loss: 1.04
Batch: #1/38, loss: 1.03
Batch: #1/39, loss: 0.83
Batch: #1/40, loss: 1.03
Batch: #1/41, loss: 1.15
Batch: #1/42, loss: 0.95
Batch: #1/43, loss: 0.92
Batch: #1/44, loss: 1.16
Batch: #1/45, loss: 0.81
Batch: #1/46, loss: 1.07
Batch: #1/47, loss: 1.05
Batch: #1/48, loss: 1.15
Batch: #1/49, loss: 1.03
Batch: #1/50, loss: 0.98
Batch: #1/51, loss: 1.16
Batch: #1/52, loss: 1.04
Batch: #1/53, loss: 1.16
Batch: #1/54, loss: 1.10
Batch: #1/55, loss: 1.01
Batch: #1/56, loss: 0.84
Batch: #1/57, loss: 0.92
Batch: #1/58, loss: 0.88
Batch: #1/59, loss: 1.21
Batch: #2/0, loss: 1.01
Batch: #2/1, loss: 1.10
Batch: #2/2, loss: 0.88
Batch: #2/3, loss: 0.97
Batch: #2/4, loss: 0.98
Batch: #2/5, loss: 1.01
Batch: #2/6, loss: 0.89
Batch: #2/7, loss: 1.02
Batch: #2/8, loss: 1.00
Batch: #2/9, loss: 0.78
Batch: #2/10, loss: 0.99
Batch: #2/11, loss: 1.08
Batch: #2/12, loss: 1.11
Batch: #2/13, loss: 1.21
Batch: #2/14, loss: 0.91
Batch: #2/15, loss: 1.20
Batch: #2/16, loss: 1.13
Batch: #2/17, loss: 0.88
Batch: #2/18, loss: 0.79
Batch: #2/19, loss: 1.13
Batch: #2/20, loss: 1.11
Batch: #2/21, loss: 1.02
Batch: #2/22, loss: 1.02
Batch: #2/23, loss: 0.97
Batch: #2/24, loss: 1.14
Batch: #2/25, loss: 1.08
Batch: #2/26, loss: 0.80
Batch: #2/27, loss: 0.92
Batch: #2/28, loss: 1.03
Batch: #2/29, loss: 1.00
Batch: #2/30, loss: 1.02
Batch: #2/31, loss: 0.85
Batch: #2/32, loss: 1.00
Batch: #2/33, loss: 0.73
Batch: #2/34, loss: 1.08
Batch: #2/35, loss: 1.05
Batch: #2/36, loss: 0.82
Batch: #2/37, loss: 1.00
Batch: #2/38, loss: 0.77
Batch: #2/39, loss: 0.79
Batch: #2/40, loss: 0.96
Batch: #2/41, loss: 0.98
Batch: #2/42, loss: 1.21
Batch: #2/43, loss: 1.20
Batch: #2/44, loss: 0.97
Batch: #2/45, loss: 0.99
Batch: #2/46, loss: 1.12
Batch: #2/47, loss: 0.83
Batch: #2/48, loss: 0.84
Batch: #2/49, loss: 0.76
Batch: #2/50, loss: 0.77
Batch: #2/51, loss: 0.94
Batch: #2/52, loss: 0.83
Batch: #2/53, loss: 1.08
Batch: #2/54, loss: 0.73
Batch: #2/55, loss: 1.01
Batch: #2/56, loss: 0.94
Batch: #2/57, loss: 1.07
Batch: #2/58, loss: 0.94
Batch: #2/59, loss: 1.02
Batch: #3/0, loss: 1.18
Batch: #3/1, loss: 1.19
Batch: #3/2, loss: 0.90
Batch: #3/3, loss: 0.91
Batch: #3/4, loss: 0.67
Batch: #3/5, loss: 0.75
Batch: #3/6, loss: 0.92
Batch: #3/7, loss: 1.15
Batch: #3/8, loss: 0.69
Batch: #3/9, loss: 0.91
Batch: #3/10, loss: 0.79
Batch: #3/11, loss: 1.06
Batch: #3/12, loss: 0.95
Batch: #3/13, loss: 1.16
Batch: #3/14, loss: 0.67
Batch: #3/15, loss: 0.74
Batch: #3/16, loss: 0.83
Batch: #3/17, loss: 0.91
Batch: #3/18, loss: 1.14
Batch: #3/19, loss: 0.71
Batch: #3/20, loss: 1.08
Batch: #3/21, loss: 0.82
Batch: #3/22, loss: 0.73
Batch: #3/23, loss: 0.89
Batch: #3/24, loss: 1.01
Batch: #3/25, loss: 1.03
Batch: #3/26, loss: 0.64
Batch: #3/27, loss: 0.69
Batch: #3/28, loss: 0.79
Batch: #3/29, loss: 0.88
Batch: #3/30, loss: 0.76
Batch: #3/31, loss: 1.12
Batch: #3/32, loss: 1.07
Batch: #3/33, loss: 0.59
Batch: #3/34, loss: 1.14
Batch: #3/35, loss: 1.18
Batch: #3/36, loss: 0.97
Batch: #3/37, loss: 0.99
Batch: #3/38, loss: 0.73
Batch: #3/39, loss: 1.15
Batch: #3/40, loss: 0.67
Batch: #3/41, loss: 0.88
Batch: #3/42, loss: 0.94
Batch: #3/43, loss: 0.89
Batch: #3/44, loss: 0.87
Batch: #3/45, loss: 0.85
Batch: #3/46, loss: 0.74
Batch: #3/47, loss: 0.88
Batch: #3/48, loss: 0.72
Batch: #3/49, loss: 1.01
Batch: #3/50, loss: 0.73
Batch: #3/51, loss: 0.63
Batch: #3/52, loss: 0.60
Batch: #3/53, loss: 0.82
Batch: #3/54, loss: 0.76
Batch: #3/55, loss: 1.00
Batch: #3/56, loss: 0.66
Batch: #3/57, loss: 1.20
Batch: #3/58, loss: 0.65
Batch: #3/59, loss: 0.66
Batch: #4/0, loss: 0.75
Batch: #4/1, loss: 0.77
Batch: #4/2, loss: 0.97
Batch: #4/3, loss: 0.65
Batch: #4/4, loss: 0.63
Batch: #4/5, loss: 0.95
Batch: #4/6, loss: 0.86
Batch: #4/7, loss: 0.67
Batch: #4/8, loss: 0.88
Batch: #4/9, loss: 0.50
Batch: #4/10, loss: 0.88
Batch: #4/11, loss: 0.85
Batch: #4/12, loss: 1.20
Batch: #4/13, loss: 0.84
Batch: #4/14, loss: 0.71
Batch: #4/15, loss: 1.09
Batch: #4/16, loss: 0.87
Batch: #4/17, loss: 0.65
Batch: #4/18, loss: 0.57
Batch: #4/19, loss: 0.53
Batch: #4/20, loss: 0.56
Batch: #4/21, loss: 0.86
Batch: #4/22, loss: 0.54
Batch: #4/23, loss: 0.98
Batch: #4/24, loss: 0.56
Batch: #4/25, loss: 1.20
Batch: #4/26, loss: 0.91
Batch: #4/27, loss: 0.85
Batch: #4/28, loss: 0.79
Batch: #4/29, loss: 0.91
Batch: #4/30, loss: 0.91
Batch: #4/31, loss: 0.82
Batch: #4/32, loss: 0.88
Batch: #4/33, loss: 0.57
Batch: #4/34, loss: 0.47
Batch: #4/35, loss: 0.76
Batch: #4/36, loss: 0.83
Batch: #4/37, loss: 0.78
Batch: #4/38, loss: 0.77
Batch: #4/39, loss: 0.77
Batch: #4/40, loss: 0.83
Batch: #4/41, loss: 0.48
Batch: #4/42, loss: 0.77
Batch: #4/43, loss: 0.73
Batch: #4/44, loss: 0.49
Batch: #4/45, loss: 0.75
Batch: #4/46, loss: 0.53
Batch: #4/47, loss: 0.88
Batch: #4/48, loss: 0.78
Batch: #4/49, loss: 0.66
Batch: #4/50, loss: 0.44
Batch: #4/51, loss: 0.59
Batch: #4/52, loss: 1.19
Batch: #4/53, loss: 0.77
Batch: #4/54, loss: 0.80
Batch: #4/55, loss: 0.51
Batch: #4/56, loss: 0.92
Batch: #4/57, loss: 0.74
Batch: #4/58, loss: 0.73
Batch: #4/59, loss: 0.86
Batch: #5/0, loss: 0.74
Batch: #5/1, loss: 0.63
Batch: #5/2, loss: 0.45
Batch: #5/3, loss: 1.09
Batch: #5/4, loss: 0.55
Batch: #5/5, loss: 0.49
Batch: #5/6, loss: 0.59
Batch: #5/7, loss: 0.38
Batch: #5/8, loss: 0.88
Batch: #5/9, loss: 0.88
Batch: #5/10, loss: 0.45
Batch: #5/11, loss: 0.75
Batch: #5/12, loss: 0.77
Batch: #5/13, loss: 0.81
Batch: #5/14, loss: 1.03
Batch: #5/15, loss: 0.54
Batch: #5/16, loss: 0.88
Batch: #5/17, loss: 0.43
Batch: #5/18, loss: 1.12
Batch: #5/19, loss: 1.15
Batch: #5/20, loss: 0.69
Batch: #5/21, loss: 1.04
Batch: #5/22, loss: 0.76
Batch: #5/23, loss: 0.66
Batch: #5/24, loss: 0.67
Batch: #5/25, loss: 1.00
Batch: #5/26, loss: 0.40
Batch: #5/27, loss: 0.39
Batch: #5/28, loss: 0.35
Batch: #5/29, loss: 1.08
Batch: #5/30, loss: 0.73
Batch: #5/31, loss: 0.50
Batch: #5/32, loss: 0.63
Batch: #5/33, loss: 0.55
Batch: #5/34, loss: 0.71
Batch: #5/35, loss: 0.64
Batch: #5/36, loss: 0.35
Batch: #5/37, loss: 0.36
Batch: #5/38, loss: 0.83
Batch: #5/39, loss: 0.70
Batch: #5/40, loss: 0.49
Batch: #5/41, loss: 0.80
Batch: #5/42, loss: 0.26
Batch: #5/43, loss: 0.68
Batch: #5/44, loss: 0.60
Batch: #5/45, loss: 0.48
Batch: #5/46, loss: 0.78
Batch: #5/47, loss: 0.33
Batch: #5/48, loss: 0.35
Batch: #5/49, loss: 0.72
Batch: #5/50, loss: 0.65
Batch: #5/51, loss: 0.29
Batch: #5/52, loss: 1.02
Batch: #5/53, loss: 0.59
Batch: #5/54, loss: 0.33
Batch: #5/55, loss: 0.88
Batch: #5/56, loss: 0.65
Batch: #5/57, loss: 0.57
Batch: #5/58, loss: 0.73
Batch: #5/59, loss: 0.83
Batch: #6/0, loss: 0.25
Batch: #6/1, loss: 0.68
Batch: #6/2, loss: 0.65
Batch: #6/3, loss: 0.65
Batch: #6/4, loss: 0.79
Batch: #6/5, loss: 0.38
Batch: #6/6, loss: 0.63
Batch: #6/7, loss: 0.81
Batch: #6/8, loss: 0.27
Batch: #6/9, loss: 0.28
Batch: #6/10, loss: 1.16
Batch: #6/11, loss: 0.97
Batch: #6/12, loss: 1.14
Batch: #6/13, loss: 0.87
Batch: #6/14, loss: 0.36
Batch: #6/15, loss: 0.62
Batch: #6/16, loss: 0.57
Batch: #6/17, loss: 0.65
Batch: #6/18, loss: 0.49
Batch: #6/19, loss: 0.58
Batch: #6/20, loss: 0.79
Batch: #6/21, loss: 0.44
Batch: #6/22, loss: 0.68
Batch: #6/23, loss: 0.59
Batch: #6/24, loss: 0.61
Batch: #6/25, loss: 0.42
Batch: #6/26, loss: 0.75
Batch: #6/27, loss: 0.95
Batch: #6/28, loss: 0.66
Batch: #6/29, loss: 0.40
Batch: #6/30, loss: 0.54
Batch: #6/31, loss: 0.85
Batch: #6/32, loss: 1.03
Batch: #6/33, loss: 0.76
Batch: #6/34, loss: 0.31
Batch: #6/35, loss: 0.29
Batch: #6/36, loss: 0.62
Batch: #6/37, loss: 0.25
Batch: #6/38, loss: 0.71
Batch: #6/39, loss: 0.68
Batch: #6/40, loss: 0.47
Batch: #6/41, loss: 0.77
Batch: #6/42, loss: 0.78
Batch: #6/43, loss: 0.68
Batch: #6/44, loss: 0.53
Batch: #6/45, loss: 0.43
Batch: #6/46, loss: 0.45
Batch: #6/47, loss: 0.20
Batch: #6/48, loss: 0.47
Batch: #6/49, loss: 0.63
Batch: #6/50, loss: 0.27
Batch: #6/51, loss: 0.21
Batch: #6/52, loss: 0.35
Batch: #6/53, loss: 0.23
Batch: #6/54, loss: 0.51
Batch: #6/55, loss: 0.18
Batch: #6/56, loss: 0.56
Batch: #6/57, loss: 0.92
Batch: #6/58, loss: 0.40
Batch: #6/59, loss: 0.21
Batch: #7/0, loss: 0.43
Batch: #7/1, loss: 0.81
Batch: #7/2, loss: 0.37
Batch: #7/3, loss: 0.73
Batch: #7/4, loss: 0.66
Batch: #7/5, loss: 0.98
Batch: #7/6, loss: 0.29
Batch: #7/7, loss: 0.58
Batch: #7/8, loss: 0.56
Batch: #7/9, loss: 0.96
Batch: #7/10, loss: 0.20
Batch: #7/11, loss: 0.59
Batch: #7/12, loss: 0.71
Batch: #7/13, loss: 0.63
Batch: #7/14, loss: 0.95
Batch: #7/15, loss: 0.46
Batch: #7/16, loss: 0.62
Batch: #7/17, loss: 0.69
Batch: #7/18, loss: 0.88
Batch: #7/19, loss: 0.23
Batch: #7/20, loss: 0.40
Batch: #7/21, loss: 0.42
Batch: #7/22, loss: 0.56
Batch: #7/23, loss: 0.24
Batch: #7/24, loss: 0.24
Batch: #7/25, loss: 0.21
Batch: #7/26, loss: 0.57
Batch: #7/27, loss: 0.20
Batch: #7/28, loss: 0.16
Batch: #7/29, loss: 0.94
Batch: #7/30, loss: 0.23
Batch: #7/31, loss: 0.60
Batch: #7/32, loss: 0.57
Batch: #7/33, loss: 0.14
Batch: #7/34, loss: 0.71
Batch: #7/35, loss: 0.60
Batch: #7/36, loss: 0.54
Batch: #7/37, loss: 0.31
Batch: #7/38, loss: 0.28
Batch: #7/39, loss: 0.64
Batch: #7/40, loss: 0.69
Batch: #7/41, loss: 0.17
Batch: #7/42, loss: 0.53
Batch: #7/43, loss: 0.14
Batch: #7/44, loss: 0.14
Batch: #7/45, loss: 0.17
Batch: #7/46, loss: 0.35
Batch: #7/47, loss: 0.92
Batch: #7/48, loss: 0.31
Batch: #7/49, loss: 0.21
Batch: #7/50, loss: 0.87
Batch: #7/51, loss: 0.86
Batch: #7/52, loss: 0.19
Batch: #7/53, loss: 0.71
Batch: #7/54, loss: 0.87
Batch: #7/55, loss: 0.21
Batch: #7/56, loss: 0.63
Batch: #7/57, loss: 0.51
Batch: #7/58, loss: 0.54
Batch: #7/59, loss: 0.63
Batch: #8/0, loss: 0.58
Batch: #8/1, loss: 0.22
Batch: #8/2, loss: 0.50
Batch: #8/3, loss: 0.55
Batch: #8/4, loss: 0.14
Batch: #8/5, loss: 0.11
Batch: #8/6, loss: 0.36
Batch: #8/7, loss: 0.65
Batch: #8/8, loss: 0.12
Batch: #8/9, loss: 0.58
Batch: #8/10, loss: 0.23
Batch: #8/11, loss: 0.71
Batch: #8/12, loss: 0.88
Batch: #8/13, loss: 0.53
Batch: #8/14, loss: 0.31
Batch: #8/15, loss: 0.29
Batch: #8/16, loss: 0.35
Batch: #8/17, loss: 0.23
Batch: #8/18, loss: 0.88
Batch: #8/19, loss: 0.84
Batch: #8/20, loss: 0.26
Batch: #8/21, loss: 0.49
Batch: #8/22, loss: 0.80
Batch: #8/23, loss: 0.18
Batch: #8/24, loss: 0.71
Batch: #8/25, loss: 0.10
Batch: #8/26, loss: 0.57
Batch: #8/27, loss: 0.43
Batch: #8/28, loss: 0.69
Batch: #8/29, loss: 0.79
Batch: #8/30, loss: 0.40
Batch: #8/31, loss: 0.26
Batch: #8/32, loss: 0.61
Batch: #8/33, loss: 0.27
Batch: #8/34, loss: 0.69
Batch: #8/35, loss: 0.51
Batch: #8/36, loss: 0.80
Batch: #8/37, loss: 0.63
Batch: #8/38, loss: 0.34
Batch: #8/39, loss: 0.64
Batch: #8/40, loss: 0.25
Batch: #8/41, loss: 0.51
Batch: #8/42, loss: 0.42
Batch: #8/43, loss: 0.40
Batch: #8/44, loss: 0.72
Batch: #8/45, loss: 0.51
Batch: #8/46, loss: 0.12
Batch: #8/47, loss: 0.61
Batch: #8/48, loss: 0.50
Batch: #8/49, loss: 0.48
Batch: #8/50, loss: 0.37
Batch: #8/51, loss: 0.42
Batch: #8/52, loss: 0.71
Batch: #8/53, loss: 0.42
Batch: #8/54, loss: 0.22
Batch: #8/55, loss: 0.22
Batch: #8/56, loss: 0.17
Batch: #8/57, loss: 0.37
Batch: #8/58, loss: 0.64
Batch: #8/59, loss: 0.40
Batch: #9/0, loss: 0.51
Batch: #9/1, loss: 0.55
Batch: #9/2, loss: 0.54
Batch: #9/3, loss: 0.24
Batch: #9/4, loss: 0.18
Batch: #9/5, loss: 0.19
Batch: #9/6, loss: 0.30
Batch: #9/7, loss: 0.57
Batch: #9/8, loss: 1.11
Batch: #9/9, loss: 0.37
Batch: #9/10, loss: 0.56
Batch: #9/11, loss: 0.66
Batch: #9/12, loss: 0.78
Batch: #9/13, loss: 0.15
Batch: #9/14, loss: 0.34
Batch: #9/15, loss: 0.48
Batch: #9/16, loss: 0.31
Batch: #9/17, loss: 0.51
Batch: #9/18, loss: 0.76
Batch: #9/19, loss: 0.66
Batch: #9/20, loss: 0.25
Batch: #9/21, loss: 0.08
Batch: #9/22, loss: 0.50
Batch: #9/23, loss: 0.98
Batch: #9/24, loss: 0.64
Batch: #9/25, loss: 0.54
Batch: #9/26, loss: 0.98
Batch: #9/27, loss: 0.48
Batch: #9/28, loss: 0.73
Batch: #9/29, loss: 0.83
Batch: #9/30, loss: 0.48
Batch: #9/31, loss: 0.33
Batch: #9/32, loss: 0.08
Batch: #9/33, loss: 0.08
Batch: #9/34, loss: 0.42
Batch: #9/35, loss: 0.40
Batch: #9/36, loss: 0.07
Batch: #9/37, loss: 0.40
Batch: #9/38, loss: 0.36
Batch: #9/39, loss: 0.20
Batch: #9/40, loss: 0.06
Batch: #9/41, loss: 0.42
Batch: #9/42, loss: 0.42
Batch: #9/43, loss: 0.10
Batch: #9/44, loss: 0.07
Batch: #9/45, loss: 0.07
Batch: #9/46, loss: 0.17
Batch: #9/47, loss: 0.43
Batch: #9/48, loss: 0.44
Batch: #9/49, loss: 0.58
Batch: #9/50, loss: 0.74
Batch: #9/51, loss: 0.37
Batch: #9/52, loss: 0.36
Batch: #9/53, loss: 0.14
Batch: #9/54, loss: 0.49
Batch: #9/55, loss: 0.23
Batch: #9/56, loss: 0.10
Batch: #9/57, loss: 0.53
Batch: #9/58, loss: 0.76
Batch: #9/59, loss: 0.41
Batch: #10/0, loss: 0.24
Batch: #10/1, loss: 0.06
Batch: #10/2, loss: 0.13
Batch: #10/3, loss: 0.36
Batch: #10/4, loss: 0.19
Batch: #10/5, loss: 0.14
Batch: #10/6, loss: 0.46
Batch: #10/7, loss: 0.41
Batch: #10/8, loss: 0.07
Batch: #10/9, loss: 0.38
Batch: #10/10, loss: 0.52
Batch: #10/11, loss: 0.40
Batch: #10/12, loss: 0.50
Batch: #10/13, loss: 0.40
Batch: #10/14, loss: 0.21
Batch: #10/15, loss: 0.68
Batch: #10/16, loss: 0.35
Batch: #10/17, loss: 0.06
Batch: #10/18, loss: 0.33
Batch: #10/19, loss: 0.66
Batch: #10/20, loss: 0.09
Batch: #10/21, loss: 0.53
Batch: #10/22, loss: 0.63
Batch: #10/23, loss: 0.56
Batch: #10/24, loss: 0.87
Batch: #10/25, loss: 0.50
Batch: #10/26, loss: 0.55
Batch: #10/27, loss: 0.65
Batch: #10/28, loss: 0.40
Batch: #10/29, loss: 0.35
Batch: #10/30, loss: 0.06
Batch: #10/31, loss: 0.67
Batch: #10/32, loss: 0.25
Batch: #10/33, loss: 0.23
Batch: #10/34, loss: 0.26
Batch: #10/35, loss: 0.12
Batch: #10/36, loss: 0.06
Batch: #10/37, loss: 0.56
Batch: #10/38, loss: 0.69
Batch: #10/39, loss: 0.23
Batch: #10/40, loss: 0.55
Batch: #10/41, loss: 0.41
Batch: #10/42, loss: 0.99
Batch: #10/43, loss: 0.29
Batch: #10/44, loss: 0.85
Batch: #10/45, loss: 0.30
Batch: #10/46, loss: 0.17
Batch: #10/47, loss: 0.12
Batch: #10/48, loss: 0.69
Batch: #10/49, loss: 0.68
Batch: #10/50, loss: 0.34
Batch: #10/51, loss: 0.54
Batch: #10/52, loss: 0.47
Batch: #10/53, loss: 0.58
Batch: #10/54, loss: 0.46
Batch: #10/55, loss: 0.28
Batch: #10/56, loss: 0.05
Batch: #10/57, loss: 0.32
Batch: #10/58, loss: 0.66
Batch: #10/59, loss: 0.22
Batch: #11/0, loss: 0.25
Batch: #11/1, loss: 0.41
Batch: #11/2, loss: 0.47
Batch: #11/3, loss: 0.42
Batch: #11/4, loss: 0.23
Batch: #11/5, loss: 0.27
Batch: #11/6, loss: 0.04
Batch: #11/7, loss: 0.69
Batch: #11/8, loss: 0.38
Batch: #11/9, loss: 0.48
Batch: #11/10, loss: 0.52
Batch: #11/11, loss: 0.53
Batch: #11/12, loss: 0.06
Batch: #11/13, loss: 0.44
Batch: #11/14, loss: 0.14
Batch: #11/15, loss: 0.08
Batch: #11/16, loss: 0.58
Batch: #11/17, loss: 0.80
Batch: #11/18, loss: 0.33
Batch: #11/19, loss: 0.93
Batch: #11/20, loss: 0.39
Batch: #11/21, loss: 0.50
Batch: #11/22, loss: 0.04
Batch: #11/23, loss: 0.04
Batch: #11/24, loss: 0.41
Batch: #11/25, loss: 0.06
Batch: #11/26, loss: 0.27
Batch: #11/27, loss: 0.36
Batch: #11/28, loss: 0.34
Batch: #11/29, loss: 0.33
Batch: #11/30, loss: 0.10
Batch: #11/31, loss: 0.55
Batch: #11/32, loss: 0.57
Batch: #11/33, loss: 0.48
Batch: #11/34, loss: 0.68
Batch: #11/35, loss: 0.54
Batch: #11/36, loss: 0.18
Batch: #11/37, loss: 0.27
Batch: #11/38, loss: 0.06
Batch: #11/39, loss: 0.51
Batch: #11/40, loss: 0.36
Batch: #11/41, loss: 0.05
Batch: #11/42, loss: 0.04
Batch: #11/43, loss: 0.32
Batch: #11/44, loss: 0.47
Batch: #11/45, loss: 1.05
Batch: #11/46, loss: 0.34
Batch: #11/47, loss: 0.54
Batch: #11/48, loss: 0.83
Batch: #11/49, loss: 0.37
Batch: #11/50, loss: 0.37
Batch: #11/51, loss: 0.53
Batch: #11/52, loss: 0.19
Batch: #11/53, loss: 0.14
Batch: #11/54, loss: 0.40
Batch: #11/55, loss: 0.16
Batch: #11/56, loss: 0.38
Batch: #11/57, loss: 0.11
Batch: #11/58, loss: 0.27
Batch: #11/59, loss: 0.60
Batch: #12/0, loss: 0.12
Batch: #12/1, loss: 0.60
Batch: #12/2, loss: 0.39
Batch: #12/3, loss: 0.87
Batch: #12/4, loss: 0.21
Batch: #12/5, loss: 0.15
Batch: #12/6, loss: 0.89
Batch: #12/7, loss: 0.60
Batch: #12/8, loss: 0.91
Batch: #12/9, loss: 0.55
Batch: #12/10, loss: 0.36
Batch: #12/11, loss: 0.31
Batch: #12/12, loss: 0.18
Batch: #12/13, loss: 0.12
Batch: #12/14, loss: 0.40
Batch: #12/15, loss: 0.21
Batch: #12/16, loss: 0.64
Batch: #12/17, loss: 0.48
Batch: #12/18, loss: 0.49
Batch: #12/19, loss: 0.04
Batch: #12/20, loss: 0.34
Batch: #12/21, loss: 0.54
Batch: #12/22, loss: 0.39
Batch: #12/23, loss: 0.29
Batch: #12/24, loss: 0.75
Batch: #12/25, loss: 0.12
Batch: #12/26, loss: 0.33
Batch: #12/27, loss: 0.56
Batch: #12/28, loss: 0.46
Batch: #12/29, loss: 0.38
Batch: #12/30, loss: 0.34
Batch: #12/31, loss: 0.36
Batch: #12/32, loss: 0.53
Batch: #12/33, loss: 0.39
Batch: #12/34, loss: 0.24
Batch: #12/35, loss: 0.21
Batch: #12/36, loss: 0.45
Batch: #12/37, loss: 0.31
Batch: #12/38, loss: 0.62
Batch: #12/39, loss: 0.44
Batch: #12/40, loss: 0.24
Batch: #12/41, loss: 0.19
Batch: #12/42, loss: 0.04
Batch: #12/43, loss: 0.05
Batch: #12/44, loss: 0.22
Batch: #12/45, loss: 0.16
Batch: #12/46, loss: 0.13
Batch: #12/47, loss: 0.20
Batch: #12/48, loss: 0.05
Batch: #12/49, loss: 0.38
Batch: #12/50, loss: 0.44
Batch: #12/51, loss: 0.03
Batch: #12/52, loss: 0.23
Batch: #12/53, loss: 0.31
Batch: #12/54, loss: 0.23
Batch: #12/55, loss: 0.03
Batch: #12/56, loss: 0.03
Batch: #12/57, loss: 0.34
Batch: #12/58, loss: 0.73
Batch: #12/59, loss: 0.40
Batch: #13/0, loss: 0.56
Batch: #13/1, loss: 0.10
Batch: #13/2, loss: 0.29
Batch: #13/3, loss: 0.38
Batch: #13/4, loss: 0.24
Batch: #13/5, loss: 0.38
Batch: #13/6, loss: 0.05
Batch: #13/7, loss: 0.62
Batch: #13/8, loss: 0.19
Batch: #13/9, loss: 0.48
Batch: #13/10, loss: 0.68
Batch: #13/11, loss: 0.54
Batch: #13/12, loss: 0.47
Batch: #13/13, loss: 0.10
Batch: #13/14, loss: 0.56
Batch: #13/15, loss: 0.27
Batch: #13/16, loss: 0.49

In [98]:
model.eval()
for (idx, (x, y)) in enumerate(test_dataloader):
    with torch.no_grad():
        x = x.float()

        outputs = torch.argmax(torch.softmax(model(x), dim=1), dim=1)
        print(f'Batch: #{idx}, output: {outputs}, y: {y}')

Batch: #0, output: tensor([0, 2]), y: tensor([0, 2])
Batch: #1, output: tensor([1, 1]), y: tensor([1, 1])
Batch: #2, output: tensor([0, 1]), y: tensor([0, 1])
Batch: #3, output: tensor([0, 0]), y: tensor([0, 0])
Batch: #4, output: tensor([2, 1]), y: tensor([2, 1])
Batch: #5, output: tensor([2, 2]), y: tensor([2, 2])
Batch: #6, output: tensor([2, 1]), y: tensor([2, 1])
Batch: #7, output: tensor([0, 0]), y: tensor([0, 0])
Batch: #8, output: tensor([0, 1]), y: tensor([0, 1])
Batch: #9, output: tensor([1, 2]), y: tensor([1, 2])
Batch: #10, output: tensor([0, 2]), y: tensor([0, 2])
Batch: #11, output: tensor([1, 1]), y: tensor([1, 2])
Batch: #12, output: tensor([2, 2]), y: tensor([2, 1])
Batch: #13, output: tensor([1, 0]), y: tensor([1, 0])
Batch: #14, output: tensor([2, 0]), y: tensor([2, 0])

точность

In [99]:
def accuracy(model, dataloader):
    model.eval()
    correct = 0
    total = 0

    for x, y in dataloader:
        with torch.no_grad():
            x = x.float()

            outputs = model(x)
            predictions = torch.argmax(outputs, dim=1)

            correct += (predictions == y).sum().item()
            total += y.size(0)

    return 100 * correct / total

tr = accuracy(model, train_dataloader)
tst = accuracy(model, test_dataloader)

print(f"Точность на тренировочных: {tr:.1f}%")
print(f"на тестовых:  {tst:.1f}%")

Точность на тренировочных: 97.5%
на тестовых:  93.3%